name: Build & Test

on:
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build-and-test.yml"
      - ".vscode/**"
      - "doc/**"
      - "lifecycle/**"
      - ".gitignore"
      - "README.md"
  pull_request:

jobs:
  i18n:
    name: Generate i18n catalog
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm build:deps

      - name: Extract catalogs
        run: |
          pnpm --filter client lingui:extract
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Stoat CI
          author_email: stoat-ci@users.noreply.github.com
          message: "chore: generate i18n catalog"

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    if: always()
    needs:
      - i18n

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm build:deps

      - name: Run typecheck
        run: pnpm test:typecheck

  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest

    if: always()
    needs:
      - i18n

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm build:deps

      - name: Run linter
        run: pnpm test:lint
      - name: Run formatter
        run: pnpm test:fmt

  e2e:
    name: e2e Integration Test
    runs-on: ubuntu-latest

    if: always()
    needs:
      - i18n

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm build:deps

      - name: Install Playwright Browsers
        run: pnpm --filter client exec playwright install --with-deps
      - name: Build web app
        run: pnpm build:web
      - name: Run Playwright tests
        run: pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/client/playwright-report/
          retention-days: 30

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: write

  #   if: github.ref == 'refs/heads/main'

  #   needs:
  #     - typecheck
  #     - e2e
  #     - lint-format
    
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: recursive
  #     - run: |
  #         git fetch origin stable:stable
  #         git push origin main:stable -f
